# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Services that make up the entire application stack of Typeahead application
services:
  lb:
    container_name: lb
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always  
    tty: true
    depends_on:
      - service1
    networks:
      - network1

  # Typeahead React based UI service 
  ui:
    container_name: ui
    build:
      context: typeahead-react # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    tty: true
    depends_on:
      - lb
    networks:
      - network1
  
  # Spring boot based typeahead Rest Api
  service1:
    container_name: service1
    build:
      context: typeahead-rest-api # Use an image built from the specified dockerfile in the `polling-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8181:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always  
    tty: true
    links:
      - es
    depends_on:
      - es 
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - network1

  # Elastic search service
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - network1

volumes:
  es-data:
    driver: local

# Networks to be created to facilitate communication between containers
networks:
  network1:
